# Generated by Django 5.2.4 on 2025-09-15 20:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('out_trade_no', models.CharField(max_length=100, unique=True)),
                ('partner_id', models.CharField(default='2018082000010170', max_length=50)),
                ('seller_id', models.CharField(default='2018082000010170', max_length=50)),
                ('appid', models.CharField(default='2018082000010171', max_length=50)),
                ('prepay_id', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MMK', max_length=3)),
                ('subject', models.CharField(max_length=255)),
                ('trade_status', models.CharField(choices=[('PENDING', 'Pending'), ('TRADE_SUCCESS', 'Trade Success'), ('TRADE_FAILED', 'Trade Failed'), ('TRADE_CANCELED', 'Trade Canceled')], default='PENDING', max_length=20)),
                ('notify_url', models.URLField()),
                ('qrcode', models.TextField()),
                ('callback_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
