# Generated by Django 5.2.4 on 2025-09-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbzpay_mock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockpaymenttransaction',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='mockpaymenttransaction',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mockpaymenttransaction',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mockpaymenttransaction',
            name='merchant_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockpaymenttransaction',
            name='merchant_name',
            field=models.CharField(default='LaptopMart Myanmar', max_length=255),
        ),
        migrations.AddField(
            model_name='mockpaymenttransaction',
            name='order_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mockpaymenttransaction',
            name='qr_code_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mockpaymenttransaction',
            name='session_timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockpaymenttransaction',
            name='shipping_address',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
