# Generated by Django 5.1.3 on 2025-03-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.CharField(default='intel', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(default='8', max_length=100),
        ),
    ]
