# Generated by Django 5.1.3 on 2025-03-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0003_product_cpu_product_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.CharField(default='unique', max_length=100),
        ),
    ]
