# Generated by Django 5.1.4 on 2025-03-18 21:14

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0004_product_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghi12345', length=10, max_length=20, prefix='brand', unique=True)),
                ('title', models.CharField(default='Apple', max_length=100)),
                ('brand_image', models.ImageField(default='brand.jpg', upload_to='brand')),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='descripton',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='descripton',
            new_name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_products', to='flame.brand'),
        ),
    ]
