# Generated by Django 5.1.4 on 2025-03-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0005_brand_rename_descripton_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(),
        ),
    ]
