# Generated by Django 5.1.4 on 2025-04-16 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0008_cartorder_shop_shop_paypal_email_alter_shop_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='paypal_email',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('accessory', 'Accessory')], default='Laptops', max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        # migrations.AddField(
        #     model_name='shop',
        #     name='slug',
        #     field=models.SlugField(default='shop', unique=True),
        # ),
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(null=True, unique=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProxy',
        ),
    ]
