# Generated by Django 5.1.4 on 2025-04-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0012_alter_shop_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='slug',
        ),
    ]
