# Generated by Django 5.1.4 on 2025-04-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0014_alter_shop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
