# Generated by Django 5.1.4 on 2025-05-03 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0020_cartorder_order_type_cartorder_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flame.product'),
        ),
    ]
