# Generated by Django 5.1.4 on 2025-05-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0021_cartorderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
