# Generated by Django 5.2.4 on 2025-07-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0023_wishlist_shop_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='shop',
        ),
    ]
