# Generated by Django 5.2.4 on 2025-08-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0024_alter_wishlist_unique_together_remove_wishlist_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='title_en',
            field=models.CharField(default='Apple', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='title_my',
            field=models.CharField(default='Apple', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(default='Laptops', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_my',
            field=models.CharField(default='Laptops', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu_en',
            field=models.CharField(default='intel', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu_my',
            field=models.CharField(default='intel', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, default='This is the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_my',
            field=models.TextField(blank=True, default='This is the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_en',
            field=models.CharField(default='8 GB', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_my',
            field=models.CharField(default='8 GB', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_my',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(default='Macbook', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_my',
            field=models.CharField(default='Macbook', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='address_en',
            field=models.CharField(default='123 Rose Street.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='address_my',
            field=models.CharField(default='123 Rose Street.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='description_en',
            field=models.TextField(blank=True, default='Citicom Laptop Sale', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='description_my',
            field=models.TextField(blank=True, default='Citicom Laptop Sale', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='title_en',
            field=models.CharField(default='Citicom', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='title_my',
            field=models.CharField(default='Citicom', max_length=100, null=True),
        ),
    ]
