# Generated by Django 5.2.3 on 2025-08-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0025_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('deliverd', 'Delivered')], default='processing', max_length=10),
        ),
    ]
