# Generated by Django 5.2.4 on 2025-08-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0025_brand_title_en_brand_title_my_category_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='title_my',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_my',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cpu_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cpu_my',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_my',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram_my',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_my',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_my',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='address_my',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='description_my',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='title_my',
        ),
    ]
