# Generated by Django 5.2.4 on 2025-08-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0026_remove_brand_title_en_remove_brand_title_my_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='title_translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='category',
            name='title_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-translated titles'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='last_translated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='title_translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='translation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='description_translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shop',
            name='title_translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
