# Generated by Django 5.2.4 on 2025-08-19 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0027_brand_title_translations_category_title_translations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_currency_preference',
            field=models.CharField(choices=[('USD', 'USD Only'), ('MMK', 'MMK Only'), ('BOTH', 'Both')], default='BOTH', max_length=10),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(default='USD', max_length=3)),
                ('currency_to', models.CharField(default='MMK', max_length=3)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Additional markup percentage for exchange rate', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'unique_together': {('currency_from', 'currency_to')},
            },
        ),
    ]
