# Generated by Django 5.2.4 on 2025-09-12 02:53

from django.db import migrations
import uuid


def populate_order_numbers(apps, schema_editor):
    """Populate order_number for existing CartOrder records"""
    CartOrder = apps.get_model('flame', 'CartOrder')
    
    for order in CartOrder.objects.filter(order_number__isnull=True):
        # Generate unique order number based on order ID and UUID
        order_number = f"ORD-{order.id:06d}-{uuid.uuid4().hex[:6].upper()}"
        order.order_number = order_number
        order.save(update_fields=['order_number'])


def reverse_populate_order_numbers(apps, schema_editor):
    """Remove order numbers (for rollback)"""
    CartOrder = apps.get_model('flame', 'CartOrder')
    CartOrder.objects.update(order_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0029_add_ecommerce_features'),
    ]

    operations = [
        migrations.RunPython(
            populate_order_numbers,
            reverse_populate_order_numbers,
        ),
    ]
