# Generated by Django 5.2.4 on 2025-09-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0030_populate_order_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
