# Generated by Django 5.2.4 on 2025-09-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0033_add_corrected_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('kbzpay', 'KBZPay'), ('cod', 'Cash on Delivery')], default='paypal', max_length=20),
        ),
    ]
