# Generated by Django 5.2.4 on 2025-09-14 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0034_add_payment_method_to_cartorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyanmarCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_mm', models.CharField(blank=True, max_length=100)),
                ('is_major_city', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Myanmar Cities',
                'ordering': ['state__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MyanmarState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_mm', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Myanmar States',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, help_text='Near landmark', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street No, Building, etc.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street No, Building, etc.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flame.myanmarcity'),
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flame.myanmarcity'),
        ),
        migrations.AddField(
            model_name='myanmarcity',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='flame.myanmarstate'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flame.myanmarstate'),
        ),
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flame.myanmarstate'),
        ),
        migrations.CreateModel(
            name='MyanmarTownship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_mm', models.CharField(blank=True, max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='townships', to='flame.myanmarcity')),
            ],
            options={
                'verbose_name_plural': 'Myanmar Townships',
                'ordering': ['city__name', 'name'],
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.AddField(
            model_name='address',
            name='township',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flame.myanmartownship'),
        ),
        migrations.AddField(
            model_name='shop',
            name='township',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flame.myanmartownship'),
        ),
        migrations.AlterUniqueTogether(
            name='myanmarcity',
            unique_together={('state', 'name')},
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_mmk', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_same_city', models.BooleanField(default=False)),
                ('is_same_state', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_from_city', to='flame.myanmarcity')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_from', to='flame.myanmarstate')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='flame.shop')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_to_city', to='flame.myanmarcity')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_to', to='flame.myanmarstate')),
            ],
            options={
                'verbose_name_plural': 'Shipping Rates',
                'unique_together': {('shop', 'from_city', 'to_city')},
            },
        ),
    ]
