# Generated by Django 5.2.4 on 2025-09-17 13:23

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0035_myanmarcity_myanmarstate_address_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=20, max_length=40, prefix='', unique=True)),
                ('street_address', models.TextField(blank=True)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cart_data', models.JSONField(default=dict)),
                ('order_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('kbzpay', 'KBZPay'), ('cod', 'Cash on Delivery')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flame.myanmarcity')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flame.shop')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flame.myanmarstate')),
                ('township', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flame.myanmartownship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checkout Session',
                'verbose_name_plural': 'Checkout Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
