# Generated by Django 5.2.4 on 2025-09-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0026_alter_cartorder_product_status'),
        ('flame', '0037_add_payment_intent_fields'),
    ]

    operations = [
    ]
