# Generated by Django 5.2.4 on 2025-09-22 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0038_populate_myanmar_data'),
        ('flame', '0039_alter_cartorder_product_status'),
    ]

    operations = [
    ]
