# Generated by Django 5.1.4 on 2025-04-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_alter_user_bio_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shop_admin',
            field=models.BooleanField(default=False),
        ),
    ]
