# Generated by Django 5.2.4 on 2025-09-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_enhanced_authentication_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
